apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamposeml
  labels:
    app: streamposeml
spec:
  selector:
    matchLabels:
      app: streamposeml
  template:
    metadata:
      labels:
        app: streamposeml
    spec:
      containers:
        - name: streamposeml
          image: streamposeml-image
          ports:
            - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  labels:
    app: webui
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: webui-image
          ports:
            - containerPort: 3000

