name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11"]
      fail-fast: false
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync --all-groups
    
    - name: Run tests
      run: |
        uv run pytest stream_pose_ml/tests/ -v
        uv run pytest api/tests/ -v
    
    - name: Run linting
      run: |
        uv run ruff check stream_pose_ml api mlflow
        uv run ruff format --check stream_pose_ml api mlflow
    
    - name: Run type checking
      run: |
        uv run mypy stream_pose_ml api

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: uv sync --all-groups
    
    - name: Run security checks
      run: |
        uv run pip-audit --desc --ignore-vuln PYSEC-2025-52 --ignore-vuln PYSEC-2024-110